name: Publish to NPM

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*' # This will run the workflow when you push a tag with a version format, like v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: volta-cli/action@v1
    - run: npm ci --no-audit
    - run: npm run lint --if-present
    - run: npm test
    - run: npm run build --if-present
      env:
          CI: true
    - name: Setup .npmrc file to publish to npm
      run: |
        echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      env:
        NPM_TOKEN: ${{secrets.NPM_AUTOMATION_TOKEN}}
    - name: Publish to NPM
      run: npm publish